<?php

use Drupal\Core\Url;

/**
 * Implements hook_page_attachments().
 */
function reservoir_ui_page_attachments(array &$page) {
  $page['#attached']['library'][] = 'reservoir_ui/welcome';
}

function reservoir_ui_toolbar_alter(&$items) {
  unset($items['home']);

  $items['reservoir_data_manage'] = array(
    '#type' => 'toolbar_item',
    'tab' => array(
      '#type' => 'link',
      '#title' => t('Manage content'),
      '#url' => Url::fromRoute('<front>'),
      '#attributes' => array(
        'class' => array('toolbar-icon', 'toolbar-icon-system-admin-content'),
      ),
    ),
    '#weight' => -35,
  );
  $items['reservoir_api'] = array(
    '#type' => 'toolbar_item',
    'tab' => array(
      '#type' => 'link',
      '#title' => t('API'),
      '#url' => Url::fromRoute('reservoir_ui.api'),
      '#attributes' => array(
        'class' => array('toolbar-icon', 'toolbar-icon-system-modules-list'),
      ),
    ),
    '#weight' => -30,
  );
  $items['reservoir_data_model'] = array(
    '#type' => 'toolbar_item',
    'tab' => array(
      '#type' => 'link',
      '#title' => t('Model content'),
      '#url' => Url::fromRoute('entity.node_type.collection'),
      '#attributes' => array(
        'class' => array('toolbar-icon', 'toolbar-icon-system-admin-structure'),
      ),
    ),
    '#weight' => -25,
  );
  $items['reservoir_data_access'] = array(
    '#type' => 'toolbar_item',
    'tab' => array(
      '#type' => 'link',
      '#title' => t('Access control'),
      '#url' => Url::fromRoute('entity.user.collection'),
      '#attributes' => array(
        'class' => array('toolbar-icon', 'toolbar-icon-entity-user-collection'),
      ),
    ),
    '#weight' => -20,
  );

  $items['reservoir_backend'] = array(
    '#type' => 'toolbar_item',
    'tab' => array(
      '#type' => 'link',
      '#title' => t('Manage back end'),
      '#url' => Url::fromRoute('user.page'),
      '#attributes' => array(
        'class' => array('toolbar-icon', 'toolbar-icon-menu'),
      ),
    ),
    'tray' => array(
      '#heading' => t('Back end management'),
      'user_links' => array(
        '#theme' => 'links__toolbar_reservoir_ui',
        '#links' => [
          'configuration' => [
            'title' => t('Configuration'),
            'url' => Url::fromRoute('system.admin_config'),
            'attributes' => [
              'class' => [
                'toolbar-icon',
                'toolbar-icon-system-admin-config',
              ],
            ],
          ],
          'reports' => [
            'title' => t('Reports'),
            'url' => Url::fromRoute('system.admin_reports'),
            'attributes' => [
              'class' => [
                'toolbar-icon',
                'toolbar-icon-system-admin-reports',
              ],
            ],
          ],
          'help' => [
            'title' => t('Help'),
            'url' => Url::fromRoute('help.main'),
            'attributes' => [
              'class' => [
                'toolbar-icon',
                'toolbar-icon-help-main',
              ],
            ],
          ],
        ],
        '#attributes' => array(
          'class' => array('toolbar-reservoir-ui'),
        ),
      ),
    ),
    '#weight' => -15,
  );

  unset($items['administration']);


}

function reservoir_ui_menu_links_discovered_alter(&$links) {
  unset($links['system.site_information_settings']);
  unset($links['block.admin_display']);
  unset($links['system.themes_page']);
  unset($links['filter.tips_all']);
  unset($links['entity.date_format.collection']);
  unset($links['views_ui.reports_plugins']);
  unset($links['system.rss_feeds_settings']);

  $links['system.admin_content']['title'] = t('Data');
  $links['system.admin_content']['description'] = t('Find and manage data.');
  $links['system.admin_structure']['title'] = t('Data modeling');
  $links['system.admin_structure']['description'] = t('Model data: content types, comment types, taxonomies …');
  $links['system.modules_list']['parent'] = 'system.admin_config';


  $links['entity.user.collection']['weight'] = 3;
  $links['system.admin_config']['weight'] = 4;

  $links['filter.admin_overview']['parent'] = 'system.admin_structure';

  $links['system.admin_config']['title'] = t('Back end configuration');


  $links['entity.user.collection']['title'] = t('Access control');
  $links['user.admin_index']['title'] = t('Users');
}